POST http://localhost:8080/alerts
Content-Type: application/json

{
  "alerts": [
    {
      "hash": "0xe9cfda18f167de5cdd63c101e38ec0d4cb0a1c2dea80921ecc4405c2b010855f",
      "createdAt": "2022-03-01T12:24:33.379756298Z",
      "alertId": "OZ-GNOSIS-EVENTS",
      "name": "ethereum-steth-1",
      "protocol": "ethereum",
      "description": "Manual CRITICAL finding",
      "findingType": "UNKNOWN_TYPE",
      "severity": "LOW",
      "metadata": {
        "contractAddress": "0x98883145049dec03c00cb7708cbc938058802520",
        "operator": "0x1fFa3471A45C22B1284fE5a251eD74F40580a1E3"
      },
      "links": {
        "explorerUrl": "https://explorer.forta.network/alert/0xd795c365931762afeccf4a440ecee2f7e89820c59136aa46310a8eec54ba96d8",
        "blockUrl": "https://etherscan.io/block/18646150"
      },
      "source": {
        "transactionHash": "0x7040dd33cbfd3e9d880da80cb5f3697a717fc329abd0251f3dcd51599ab67b0a",
        "bot": {
          "id": "lido-on-polygon",
          "reference": "QmU6L9Zo5rweF6QZLhLfwAAFUFRMF3uFdSnMiJzENXr37R",
          "image": "bafybeibrigevnhic4befnkqbaagzgxqtdyv2fdgcbqwxe7ees3hw6fymme@sha256:9ca1547e130a6264bb1b4ad6b10f17cabf404957f23d457a30046b9afdf29fc8"
        },
        "block": {
          "number": 1235678901234,
          "hash": "0xf9e777b739cf90a197c74c461933422dcf26fadf50e0ef9aa72af76727da87ca",
          "timestamp": "2022-03-01T12:24:33Z",
          "chainId": 1337
        },
        "sourceEvent": {
          "botId": "0x17381ae942ee1fe141d0652e9dad7d001761552f906fb1684b2812603de31049",
          "alertHash": "0xe9cfda18f167de5cdd63c101e38ec0d4cb0a1c2dea80921ecc4405c2b010855f"
        }
      },
      "addresses": [
        "0x98883145049dec03c00cb7708cbc938058802520",
        "0x1fFa3471A45C22B1284fE5a251eD74F40580a1E3"
      ],
      "addressBloomFilter": {
        "k": "0x12",
        "m": "0x34",
        "bitset": "AAAAAAAAACwAAAAAAAAACwAAAAAAAAAsAAALo5gpbbc=",
        "itemCount": 1
      },
      "relatedAlerts": [
        "0xe9cfda18f167de5cdd63c101e38ec0d4cb0a1c2dea80921ecc4405c2b010855f",
        "0x533c100d5d7a56ee8448b6b08b5b1ce41ea9d1667086e1d2d4c1f03d09d191b9"
      ],
      "labels": [
        {
          "label": "scammer-eoa",
          "confidence": 0.9,
          "entity": "0x113b7cc6b42105dcb8cbfe576590cf7bbc7a12f1",
          "entityType": "ADDRESS",
          "remove": true,
          "metadata": [
            "foo=42",
            "bar=123"
          ]
        }
      ],
      "sources": {
        "transactions": [
          {
            "chainId": 0,
            "hash": "string"
          }
        ],
        "blocks": [
          {
            "chainId": 0,
            "hash": "string",
            "number": 0
          }
        ],
        "urls": [
          {
            "url": "string"
          }
        ],
        "chains": [
          {
            "chainId": 0
          }
        ],
        "alerts": [
          {
            "id": "string"
          }
        ],
        "customSources": [
          {
            "name": "string",
            "value": "string"
          }
        ]
      }
    }
  ],
  "metrics": [
    {
      "botId": "0x17381ae942ee1fe141d0652e9dad7d001761552f906fb1684b2812603de31049",
      "timestamp": "2022-03-01T12:24:33.379756298Z",
      "metrics": [
        {
          "name": "block.request",
          "count": 1337,
          "max": 537,
          "average": 47,
          "sum": 2157,
          "p95": 87
        }
      ]
    }
  ]
}