x-logging: &default-logging
  options:
    max-size: "50m"
    max-file: "10"

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10.20-alpine3.20
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js -c /etc/nats/nats.conf
    environment:
      - JS_STORAGE_DIR=/data/jetstream
    volumes:
      - ./nats/jetstream:/data/jetstream
      - ./nats/nats.conf:/etc/nats/nats.conf

  forwarder:
    image: lidofinance/onchain-mon:stable
    container_name: forwarder
    build: ./
    restart: always
    command:
      - ./forwarder
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ERRORS_CHAT_ID=${TELEGRAM_ERRORS_CHAT_ID}
      - TELEGRAM_UPDATES_CHAT_ID=${TELEGRAM_UPDATES_CHAT_ID}
      - TELEGRAM_ALERTS_CHAT_ID=${TELEGRAM_ALERTS_CHAT_ID}
      - OPSGENIE_API_KEY=${OPSGENIE_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NATS_DEFAULT_URL=${NATS_DEFAULT_URL}
      - BOT_CONTAINERS=${BOT_CONTAINERS}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - QUORUM_SIZE=${QUORUM_SIZE}
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - nats

  feeder:
    image: lidofinance/onchain-mon:stable
    container_name: feeder
    build: ./
    restart: always
    command:
      - ./feeder
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ERRORS_CHAT_ID=${TELEGRAM_ERRORS_CHAT_ID}
      - TELEGRAM_UPDATES_CHAT_ID=${TELEGRAM_UPDATES_CHAT_ID}
      - TELEGRAM_ALERTS_CHAT_ID=${TELEGRAM_ALERTS_CHAT_ID}
      - OPSGENIE_API_KEY=${OPSGENIE_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NATS_DEFAULT_URL=http://nats:4222
      - BOT_CONTAINERS=${BOT_CONTAINERS}
      - REDIS_ADDRESS=redis:6379
      - QUORUM_SIZE=${QUORUM_SIZE}
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - nats

  # l2-optimism:
  #   container_name: l2-optimism
  #   image: l2-unified
  #   restart: unless-stopped
  #   # networks:
  #   #   - forta_default
  #   depends_on:
  #     - nats
  #   environment:
  #     - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL:-https://eth.drpc.org}
  #     - L2_RPC_URL=${OPTIMISM_RPC_URL:-https://mainnet.optimism.io}
  #     # - L2_RPC_URL=https://mainnet.optimism.io
  #     - NATS_SERVER_URL=http://nats:4222
  #     - LOG_LEVEL=debug
  #   command: ["yarn", "start:optimism:prod"]

  #service-ethereum-steth-v2:
  #  container_name: ethereum-steth-v2
  #  logging: *default-logging
  #  image: monitoring/steth-v2:latest
  #  restart: unless-stopped
  #  environment:
  #    - APP_NAME=ethereum-steth-v2
  #    - INSTANCE=forta-local-host
  #    - ETHEREUM_RPC_URL=https://eth-mainnet.alchemyapi.io/v2/<your_key>
  #    - NODE_ENV=production
  #    - NATS_SERVER_URL=http://127.0.0.1:4222
  #  depends_on:
  #    - service-forta-nats
  #  ports:
  #    - "3002:3000"

  #service-l2-bridge-arbitrum-v2:
  #  container_name: l2-bridge-arbitrum-v2
  #  logging: *default-logging
  #  image: monitoring/l2-bridge-arbitrum-v2:latest
  #  restart: unless-stopped
  #  environment:
  #    - APP_NAME=l2-bridge-arbitrum-v2
  #    - INSTANCE=forta-local-host
  #    - ETHEREUM_RPC_URL=https://eth-mainnet.alchemyapi.io/v2/<your_key>
  #    - ARBITRUM_RPC_URL=https://arbitrum-one.blastapi.io/<your_key>
  #    - NODE_ENV=production
  #    - NATS_DEFAULT_URL=http://127.0.0.1:4222
  #  depends_on:
  #    - service-forta-nats
  #  ports:
  #    - "3003:3000"