x-logging: &default-logging
  options:
    max-size: "50m"
    max-file: "10"

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10.20-alpine3.20
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js -c /etc/nats/nats.conf
    environment:
      - JS_STORAGE_DIR=/data/jetstream
    volumes:
      - ./nats/jetstream:/data/jetstream
      - ./nats/nats.conf:/etc/nats/nats.conf

  forwarder:
    image: lidofinance/onchain-mon:stable
    container_name: forwarder
    build: ./
    restart: always
    command:
      - ./forwarder
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - NATS_DEFAULT_URL=http://nats:4222
      - REDIS_ADDRESS=redis:6379
      - REDIS_DB=${REDIS_DB}
      - QUORUM_SIZE=${QUORUM_SIZE}
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - nats
    volumes:
      - ./notification.yaml:/etc/forwarder/notification.yaml

  feeder:
    image: lidofinance/onchain-mon:stable
    container_name: feeder
    build: ./
    restart: always
    command:
      - ./feeder
    env_file:
      - .env
    environment:
      - READ_ENV_FROM_SHELL=true
      - ENV=${ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - NATS_DEFAULT_URL=http://nats:4222
      - REDIS_ADDRESS=redis:6379
      - BLOCK_TOPIC=${BLOCK_TOPIC}
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - nats